pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - rm -rf .public/.gitlab-ci.yml
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'