image: alpine:latest

pages:
  stage: deploy
  variables:
    GIT_DEPTH: 0
  script:
    - ls -la
    - mkdir public
    - cp index.html public/
    - cp profile.jpeg public/
    - cp -r css public/
    - cp -r js public/
  artifacts:
    paths:
      - public
  only:
    - main