image: alpine:latest

pages:
  stage: deploy
  script:
    - ls -la
    - mkdir -p public
    - cp index.html public/
    - cp profile.jpeg public/  # Asegura que se llame igual
    - cp -r js public/         # Copia toda la carpeta js
    - cp -r css public/        # Si tienes carpeta css
  artifacts:
    paths:
      - public
  only:
    - main